### ISSUE TITLE
Decrypting issue

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [Citadel-sh/BugTracker#1]
### Fuze version? (Ex. Fuze 0.1.0a)
0.1.2a
### macOS Version? (Ex. mac 10.15)
10.15.3
### Steps to reproduce 
1. Connected the device via USB
2. I have installed frida and all my other tools which requires firda works perfectly (eg objection, cracker XI etc) 
3. Open the fuze app
4. It shows all the apps list 
5. Selected the app 
6. Clicked on decrypt 
7. Asked for the device password. Entered the device passcode lock
8. Got error as shown below 
9. However the selected app opens on the device
### Screenshots (optional)
![error decrpting](https://user-images.githubusercontent.com/7692857/77044848-982b0f80-69d9-11ea-8e44-5f713037b53f.png)

**Comment by klmitchell2** [comment]
Hey thanks for checking out fuze. When you re-attach the phone, what happens?

**Comment by Cyb3rGh0st786** [comment]
@klmitchell2 

Thank you for your reply. The same error occurs even reattaching the phone

**Comment by klmitchell2** [comment]
For transparency @colealanroberts and I only have three phones between us which are all jailbroken using Checkra1n. So, we have not had a chance to test a variety of jailbroken devices, yet. What type of device are you using and which jailbreak is it using?

**Comment by colealanroberts** [comment]
Hey, happy to investigate!

7. You said device passcode lock.

You need the root password. Guessing that’s what you meant?

**Comment by Cyb3rGh0st786** [comment]
@colealanroberts 

Oh I have entered my device passcode lock  not the root password. Let me try with root password

**Comment by Cyb3rGh0st786** [comment]
@colealanroberts 

I have uninstalled fuze and installed it. Initially on the first try  I have clicked on save password option it seems it taking the previous password and not asking to enter new one. Any way I can redo it ?

**Comment by colealanroberts** [comment]
> @colealanroberts 
> 
> 
> 
> I have uninstalled fuze and installed it. Initially on the first try  I have clicked on save password option it seems it taking the previous password and not asking to enter new one. Any way I can redo it ?

If the device password is incorrect it should prompt you to retry with a different password.

If not, we can definitely release a fix that allows clearing saved data.

Try to decrypt an app and it should prompt you to enter a different device password.

**Comment by Cyb3rGh0st786** [comment]
@colealanroberts 
It's not asking me to reenter the password. Even after uninstalling fuze and installing again

**Comment by colealanroberts** [comment]
> @colealanroberts 
> 
> It's not asking me to reenter the password. Even after uninstalling fuze and installing again

What happens when you try to decrypt an app with the incorrect password? The same error as above?

I’ll write something today that will allow you to clear stored passwords. Sorry for the trouble.

**Comment by Cyb3rGh0st786** [comment]
@colealanroberts 

When I click on decrypt the same error which attached in previous screen shot appears. 

Thank you for prompt response. waiting for the fix

**Comment by klmitchell2** [comment]
@kaleemshaik7867 

Could you run `defaults delete com.citadel.Fuze`? 

This should show the password prompt again.

**Comment by Cyb3rGh0st786** [comment]
@klmitchell2 It works and asked to enter password again. However even after entering correct root password still the same error. 

Device: iphone 5s 
OS : 12.4.3
Jailbreak: Check rain

**Comment by SK-sep** [comment]
same issue

**Comment by klmitchell2** [comment]
@kaleemshaik7867 @SK-sep, could you show me the output of `python --version`?

**Comment by Cyb3rGh0st786** [comment]
Python 2.7.11

**Comment by stiabhan** [comment]
Fuze version? (Ex. Fuze 0.1.0a)

0.1.2 (1)

macOS Version? (Ex. mac 10.15)

10.15.3

Steps to reproduce

Connected to the jailbroken the device via USB
I have installed frida and the smoke test "frida-ps -u" works
Open the fuze app
It shows all the apps list
Selected the app
Clicked on decrypt
Asked for the device password. Entered the root password
Got error as shown below

Expected behavior
Dumping the decrypted app

Screenshots (optional)
As per the original post

Jailbreak

unc0ver

Python  version

3.7.7

**Comment by stiabhan** [comment]
I also entered the wrong password and had to use the defaults command to forget the bad password.
Seems better to store it only if it works?

**Comment by colealanroberts** [comment]
@stiabhan It should ask to reauthenticate if the password you provided was incorrect, even if it was stored.

This isn't likely a fix for your problem, but it will give us better insight into how we might fix the issue.

Can you visit https://getfuze.app/downloads/alpha and try again?

**Comment by Cyb3rGh0st786** [comment]
@klmitchell2 any update or workaround

**Comment by klmitchell2** [comment]
Hey @kaleemshaik7867, we are currently working on a bigger release that fixes a lot of the issues that users have seen. Hoping to have this done by the end of this week. Sorry about any delay.

**Comment by stiabhan** [comment]
Tried this again with 0.1.2a and get the exact same behaviour as described in the original post. Frida works and the smoke test runs. Trying to decrypt any loaded app always fails with "We encountered an error when reading…" - and the phone is definitely unlocked.

**Comment by colealanroberts** [comment]
Hey all, we're confident that version 0.1.3 will fix these issues. Can you please download the latest alpha from https://getfuze.app/downloads/alpha. Also, we have noticed that sometimes the UI will hang during the first launch of the new version. Can you let us know if that's the case? Thanks!

**Comment by Cyb3rGh0st786** [comment]
Hello @colealanroberts 

I am getting the following error and I am using catalina 10.15.3 

![image](https://user-images.githubusercontent.com/7692857/80355864-aba78100-8889-11ea-9d45-23c2a24173de.png)

**Comment by colealanroberts** [comment]
@kaleemshaik7867 See: https://support.apple.com/en-us/HT202491

**Comment by Cyb3rGh0st786** [comment]
@colealanroberts I have chosen `app store and identified developers` and also allowed when it pop up in the security & privacy tab after that I am getting the above error. 

I am not sure whether it's working for other or not

**Comment by klmitchell2** [comment]
Hey @kaleemshaik7867, we release v0.2.1 and hoping this could solve some of your problems. You can find it at https://www.getfuze.app. Thanks!

**Comment by Cyb3rGh0st786** [comment]
@klmitchell2 downloaded the latest version and tried and verified on friends laptop too. We are getting the error. Please note I have enabled the unidentified developers option in security & privacy section still the same error 

![image](https://user-images.githubusercontent.com/7692857/82081810-05b49d00-96f8-11ea-8634-e3b6cf3fc7be.png)

**Comment by colealanroberts** [comment]
We're planning on open sourcing Fuze soon. I'm going to close this issue for now.
