### ISSUE TITLE
won't connect to device

### ISSUE THREAD

**Issue by ipwnosx** [Citadel-sh/BugTracker#5]
### macOS Version? (Ex. mac 10.15)
10.15.4
### iOS Version
13.1.2
### Device model
iPhone7 Plus
### Screenshots (optional)
![FullSizeRender](https://user-images.githubusercontent.com/41032246/80092821-ae6c4400-8520-11ea-84be-08f8674a1de6.jpg)
won't connect to device

**Comment by colealanroberts** [comment]
@ipwnosx We're confident that version 0.1.3 will fix these issues. Can you please download the latest alpha from https://getfuze.app/downloads/alpha. Also, we have noticed that sometimes the UI will hang during the first launch of the new version. Can you let us know if that's the case? Thanks!

**Comment by ipwnosx** [comment]
Yea nope. It’s immediately crashes & won’t open

**Comment by colealanroberts** [comment]
Did you relaunch the app? If you force quit the app can you click 'Report' and paste the stack trace to Pastebin?

Thanks!
