### ISSUE TITLE
Immideiate crash

### ISSUE THREAD

**Issue by ipwnosx** [Citadel-sh/BugTracker#6]
### Screenshots (optional)

Crash-Report: Process:               Fuze [10160]
Path:                  /Applications/Fuze.app/Contents/MacOS/Fuze
Identifier:            Fuze
Version:               0.1.3 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Fuze [10160]
User ID:               501

Date/Time:             2020-04-27 07:37:16.463 -0600
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        842D30CE-0009-E01A-96AD-BB45E7D8D112

Sleep/Wake UUID:       AA65D7FF-13B2-4917-93D3-350A017EDADC

Time Awake Since Boot: 26000 seconds
Time Since Wake:       8000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib
  Referenced from: /Applications/Fuze.app/Contents/MacOS/Fuze
  Reason: image not found

Binary Images:
       0x10fbb5000 -        0x10fd44ff7 +com.citadel.Fuze (0.1.3 - 1) <63999203-BF5E-3676-B1A3-3039324B5A76> /Applications/Fuze.app/Contents/MacOS/Fuze
       0x10fdba000 -        0x10fdfcff7 +org.cocoapods.Bugsnag (5.23.0 - 1) <E00EFC94-3D85-3A06-B92E-244AA59486EE> /Applications/Fuze.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag
       0x10fe69000 -        0x10fe71ff3 +org.cocoapods.IGListDiffKit (4.0.0 - 1) <89283242-07FF-3B84-BF0F-767CBA3271FD> /Applications/Fuze.app/Contents/Frameworks/IGListDiffKit.framework/Versions/A/IGListDiffKit
       0x11a1b7000 -        0x11a248eff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld
    0x7fff2e799000 -     0x7fff2e799fff  com.apple.Cocoa (6.11 - 23) <37E98F4D-1D78-3F22-BDC0-59DC0B9B3A3E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff31d1e000 -     0x7fff320e3ff8  com.apple.Foundation (6.9 - 1675.129) <9A74FA97-7F7B-3929-B381-D9514B1E4754> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3d05c000 -     0x7fff3d0caff7  com.apple.SystemConfiguration (1.19 - 1.19) <71AC15DE-7018-3D2B-B599-F2972F0288AE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff667fd000 -     0x7fff6684ffff  libc++.1.dylib (902.1) <08199809-33CA-321E-9B9D-FD5B2BC64580> /usr/lib/libc++.1.dylib
    0x7fff68a4b000 -     0x7fff68a5dff3  libz.1.dylib (76) <6A449C6A-DF88-36C1-8F2D-DB9A808263B5> /usr/lib/libz.1.dylib

Model: Macmini4,1, BootROM MM41.0047.B00, 2 processors, Intel Core 2 Duo, 2.4 GHz, 8 GB, SMC 1.65f2
Graphics: kHW_NVidiaGeForce320MItem, NVIDIA GeForce 320M, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B44
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B52
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.31)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Hitachi HTS545032B9SA02, 320.07 GB
Serial ATA Device: HL-DT-STDVDRW  GA32N
USB Device: USB Bus
USB Device: USB Bus
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
USB Device: 2.4G RX
USB Device: USB 2.0 Bus
USB Device: USB Flash Drive
USB Device: USB2.0 Hub
USB Device: Composite Device
USB Device: USB 2.0 Bus
USB Device: Apple Mobile Device (DFU Mode)
Thunderbolt Bus:

**Comment by OsamaMahmood** [comment]
@ipwnosx could you try installing libssh2 via `brew install libssh2`?
that fixed the issue for me

**Comment by colealanroberts** [comment]
Thanks for your help @OsamaMahmood! @ipwnosx can you try running the above command and reporting back?

**Comment by ipwnosx** [comment]
![E4E0A1F2-07C8-4925-84FB-5BD1F7A1F61E](https://user-images.githubusercontent.com/41032246/80731758-90768480-8ac8-11ea-97e8-4760ed7b7495.jpeg)

**Comment by RITEKROUNAK** [comment]
> @ipwnosx could you try installing libssh2 via `brew install libssh2`?
> that fixed the issue for me

Fixed it for me too but I got that other error now

**Comment by ipwnosx** [comment]
Hey yea  confirm that solved it but I get that error

**Comment by colealanroberts** [comment]
@allanopisda3 @ipwnosx We’ve improved the error handling which also includes more verbose messaging. I’ll comment here when the next alpha build is available but you can expect it to be sometime today or tomorrow at the latest.

**Comment by ipwnosx** [comment]
released yet?

**Comment by klmitchell2** [comment]
Hey @ipwnosx, just pushed another version alpha version to https://getfuze.app/downloads/alpha

**Comment by klmitchell2** [comment]
We have released v0.2.1, you can find that here: https://www.getfuze.app. Please let us know if you find other issues. Thanks!
