### ISSUE TITLE
claims to be malware

### ISSUE THREAD

**Issue by ipwnosx** [Citadel-sh/BugTracker#7]
![Screen Shot 2020-06-05 at 2 49 58 AM](https://user-images.githubusercontent.com/41032246/83856970-910dc680-a6d7-11ea-9d07-114be7899768.png)

**Comment by ipwnosx** [comment]
claims to be malware

**Comment by klmitchell2** [comment]
Which macOS version are you running?

**Comment by ipwnosx** [comment]
Catalina

**Comment by klmitchell2** [comment]
can you provide the version number as well?

**Comment by ipwnosx** [comment]
[image: Screen Shot 2020-06-05 at 1.11.45 PM.png]

**Comment by ipwnosx** [comment]
by holding control and clicking open it does, but crashes upon opening

**Comment by colealanroberts** [comment]
> by holding control and clicking open it does, but crashes upon opening

Can you please paste the crashlog or upload to Pastebin and share a link?

**Comment by ipwnosx** [comment]
[https://pastebin.com/T97z3Rpr](url)

**Comment by OsamaMahmood** [comment]
any update on this?

**Comment by ipwnosx** [comment]
Nope

**Comment by klmitchell2** [comment]
Sorry no update on this. After trying to update the Fuze to the latest macOS versions several of our dependencies broke (Frida-swift and Shout respectively). Hoping to work on this in the future but work that pays bills has been a priority during this economy. Hope everyone can understand.

**Comment by ipwnosx** [comment]
> Sorry no update on this. After trying to update the Fuze to the latest macOS versions several of our dependencies broke (Frida-swift and Shout respectively). Hoping to work on this in the future but work that pays bills has been a priority during this economy. Hope everyone can understand.

man yeah I hear you, trying to rent dedi servers is hard enough

**Comment by klmitchell2** [comment]
We will be open sourcing the project in the near future so hopefully that helps. We will still maintain the website and push releases to that, but need to decouple our web/server code from the Fuze repo.

**Comment by HQOCBD** [comment]
Any update to this? Just downloaded the app, but am still receiving the malware message

**Comment by klmitchell2** [comment]
Sorry about that. I'll be working on removing the download link from Fuze so that this isn't confusing. I hope I can work on this more in the future but I just haven't had time.

**Comment by klmitchell2** [comment]
@HQOCBD You can use https://github.com/AloneMonkey/frida-ios-dump

**Comment by ipwnosx** [comment]
Yea that isn’t  the same at all.. non the less. I appreciate the effort so far.. and will be looking forward to a more complete edition. Ty again

**Comment by HQOCBD** [comment]
Yea, not the same, but we appreciate the effort. I was able to bypass the signature issue manually in iTerm, but am still unable to fully override the malware aspect. 

Going to try and run a malware detector on the app and see if it pulls anything and then see if there are any other overrides in iTerm that i can try.

**Comment by klmitchell2** [comment]
@HQOCBD @ipwnosx , thanks for being understanding. Although frida-ios-dump isnt graphical, its easy to use once you have everything configured (iproxy). 

Let me know if you have questions about using that tool.
